apiVersion: v1
kind: Service
metadata:
  name: hirebean-backend-service
  namespace: hirebean
spec:
  selector:
    app: hirebean-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP